"""Protocol for zero-copy bytes from Rust."""

from typing import Protocol


class Bytes(Protocol):
    """
    Protocol for zero-copy bytes returned from Rust.

    This matches the pyo3-bytes interface. Records returned from readers
    implement this protocol. Use bytes(record) or record.to_bytes() to
    convert to native Python bytes.
    """

    def __len__(self) -> int: ...
    def __bytes__(self) -> bytes: ...
    def to_bytes(self) -> bytes: ...
    def isalnum(self) -> bool: ...
    def isalpha(self) -> bool: ...
    def isascii(self) -> bool: ...
    def isdigit(self) -> bool: ...
    def islower(self) -> bool: ...
    def isspace(self) -> bool: ...
    def isupper(self) -> bool: ...
    def lower(self) -> "Bytes": ...
    def upper(self) -> "Bytes": ...
    def removeprefix(self, prefix: bytes) -> "Bytes": ...
    def removesuffix(self, suffix: bytes) -> "Bytes": ...
